---
deployment:
  tasks:
    - "export DEPLOYPATH=/home1/bgyakwmy/public_html/"
    - "/bin/cp -R palmares $DEPLOYPATH"
    - "/bin/cp -R icons $DEPLOYPATH"
    - "/bin/cp -R unete $DEPLOYPATH"
    - "/bin/cp -R valores $DEPLOYPATH"
    - "/bin/cp -R fonts $DEPLOYPATH"
    - "/bin/cp -R images $DEPLOYPATH"
    - "/bin/cp -R equipos $DEPLOYPATH"
    - "/bin/cp -R scripts $DEPLOYPATH"
    - "/bin/cp privacy.html $DEPLOYPATH"
    - "/bin/cp index.html $DEPLOYPATH"
    - "/bin/cp style.css $DEPLOYPATH"
    - "/bin/cp favicon.ico $DEPLOYPATH"
